### PR TITLE
Update to ACA-Py 0.11.0

### PR DESCRIPTION
**Pull request by frostyfrog**

### CODE REVIEW

**Comment by ff137** [comment]
I'm commenting here because it's the most recent PR

@dbluhm I notice the version in the pyproject.toml has never been bumped, and there's only one tagged release (for aca-py 0.10.4)

We want to try out this plugin, so we'll work from master - but figured it'd be good to ask for a tagged release please, just to help with version control

**Comment by dbluhm** [comment]
Thanks for the interest in the plugin @ff137! You make a good point. I'll double check the state of the pyproject.toml and most likely tag main.

**Comment by dbluhm** [comment]
@ff137 I drew a line in the sand and released the current state of main as version 0.1.0 and also tagged it (according to ACA-Py plugin convention) with `acapy-0.11.0-0`. Future changes to the minimum expected ACA-Py version will be reflected as version bumps appropriately. Hope that helps!

**Comment by dbluhm** [comment]
Based on your interest in this plugin, it may also be time for this to move to https://github.com/hyperledger/aries-acapy-plugins.

**Comment by ff137** [comment]
@dbluhm epic! Thank you 😎

**Pull request merged**
